apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "aicore-app.fullname" . } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: { { include "aicore-app.name" . } }
  template:
    metadata:
      labels:
        app: { { include "aicore-app.name" . } }
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - name: http
              containerPort: { { .Values.service.port } }
          env: { { - toYaml .Values.env | nindent 12 } }
          envFrom: { { - toYaml .Values.envFrom | nindent 12 } }
          resources: { { - toYaml .Values.resources | nindent 12 } }
