apiVersion: v1
kind: Service
metadata:
  name: { { include "aicore-app.fullname" . } }
spec:
  selector:
    app: { { include "aicore-app.name" . } }
  ports:
    - name: http
      port: { { .Values.service.port } }
      targetPort: http
