{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aicore-app.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "aicore-app.name" . }}
  endpoints:
    - port: {{ .Values.serviceMonitor.portName }}
      path: {{ .Values.serviceMonitor.path }}
      interval: 15s
{{- end }}


